---
# Get list of available pools
- name: get available pools
  virt_pool:
    command: list_pools
  register: available_pools
  become: yes
  become_user: root

# Create new pools. Does not modify existing pools.
- block:
  - name: add execute flag to user home directory
    file:
      path: '{{ ansible_user_dir }}'
      state: directory
      mode: "a+x"
    when: ansible_user_dir in libvirt_pool_dir
  - name: backup pool config if it exists
    copy:
      src: /etc/libvirt/storage/{{ libvirt_pool_name }}.xml
      dest: /etc/libvirt/storage/{{ libvirt_pool_name }}.xml.{{ ansible_date_time.epoch }}
      remote_src: yes
    ignore_errors: yes
  - name: define storage pool
    virt_pool:
      name: '{{ libvirt_pool_name }}'
      state: present
      xml: '{{ lookup("template", "pool.xml.j2") }}'
  - name: build storage pool
    virt_pool:
      command: build
      name: '{{ libvirt_pool_name }}'
  - name: start storage pool
    virt_pool:
      name: '{{ libvirt_pool_name }}'
      state: active
      autostart: yes
  become: yes
  become_user: root
  when: libvirt_pool_name not in available_pools.list_pools
...
